site_name: EcoDAM

repo_url: https://github.com/ebensteinLab/EcoDAM/

nav:
    - Home: index.md
    - User Guide:
        - BedGraphAccessor: BedGraphAccessor.md
    - API: mkapi/api/src/ecodam_py
    - Tools: tools.md
    - About: about.md

plugins:
    - search
    - mkapi
